import { DEFAULT_GAMEBOARD_DIMENSIONS } from "../utils/constants";

export const DEFAULT_OUT_OF_BOUNDS_COORDINATES = [
  [[10, 10], ...DEFAULT_GAMEBOARD_DIMENSIONS],
  [[-1, -1], ...DEFAULT_GAMEBOARD_DIMENSIONS],
  [[10, 0], ...DEFAULT_GAMEBOARD_DIMENSIONS],
  [[0, 10], ...DEFAULT_GAMEBOARD_DIMENSIONS],
  [[0, -1], ...DEFAULT_GAMEBOARD_DIMENSIONS],
  [[-1, 0], ...DEFAULT_GAMEBOARD_DIMENSIONS],
  [[15, 15], ...DEFAULT_GAMEBOARD_DIMENSIONS],
  [[-5, -5], ...DEFAULT_GAMEBOARD_DIMENSIONS],
  [[-5, 15], ...DEFAULT_GAMEBOARD_DIMENSIONS],
  [[15, -5], ...DEFAULT_GAMEBOARD_DIMENSIONS],
  [[-5, 0], ...DEFAULT_GAMEBOARD_DIMENSIONS],
  [[0, -5], ...DEFAULT_GAMEBOARD_DIMENSIONS],
  [[0, 15], ...DEFAULT_GAMEBOARD_DIMENSIONS],
  [[15, 0], ...DEFAULT_GAMEBOARD_DIMENSIONS],
  [[-5, 5], ...DEFAULT_GAMEBOARD_DIMENSIONS],
  [[5, -5], ...DEFAULT_GAMEBOARD_DIMENSIONS],
  [[5, 15], ...DEFAULT_GAMEBOARD_DIMENSIONS],
  [[15, 5], ...DEFAULT_GAMEBOARD_DIMENSIONS],
];
